CUDA_VISIBLE_DEVICES=0 python main.py --data_test MyImage --scale 2 --model DRFN --n_feats 64 --pre_train RCAN_TestCode/model/DRFN/model_best_x2.pt --test_only --save_results --chop --save 'DRFN_test' --testpath ../LR/LRBI --testset Set5
CUDA_VISIBLE_DEVICES=0 python main.py --data_test MyImage --scale 2 --model DRFN --n_feats 64 --pre_train RCAN_TestCode/model/DRFN/model_best_x2.pt --test_only --save_results --chop --save 'DRFN_final' --testpath ../LR/LRBI --testset Set14
CUDA_VISIBLE_DEVICES=0 python main.py --data_test MyImage --scale 2 --model DRFN --n_feats 64 --pre_train RCAN_TestCode/model/DRFN/model_best_x2.pt --test_only --save_results --chop --save 'DRFN_final' --testpath ../LR/LRBI --testset Urban100
CUDA_VISIBLE_DEVICES=0 python main.py --data_test MyImage --scale 2 --model DRFN --n_feats 64 --pre_train RCAN_TestCode/model/DRFN/model_best_x2.pt --test_only --save_results --chop --save 'DRFN_final' --testpath ../LR/LRBI --testset B100
CUDA_VISIBLE_DEVICES=0 python main.py --data_test MyImage --scale 2 --model DRFN --n_feats 64 --pre_train RCAN_TestCode/model/DRFN/model_best_x2.pt --test_only --save_results --chop --save 'DRFN_final' --testpath ../LR/LRBI --testset Manga109
# x3
CUDA_VISIBLE_DEVICES=0 python main.py --data_test MyImage --scale 3 --model DRFN --n_feats 64 --pre_train RCAN_TestCode/model/DRFN/model_best_x3.pt --test_only --save_results --chop --save 'DRFN_final' --testpath ../LR/LRBI --testset Set5
CUDA_VISIBLE_DEVICES=0 python main.py --data_test MyImage --scale 3 --model DRFN --n_feats 64 --pre_train RCAN_TestCode/model/DRFN/model_best_x3.pt --test_only --save_results --chop --save 'DRFN_final' --testpath ../LR/LRBI --testset Set14
CUDA_VISIBLE_DEVICES=0 python main.py --data_test MyImage --scale 3 --model DRFN --n_feats 64 --pre_train RCAN_TestCode/model/DRFN/model_best_x3.pt --test_only --save_results --chop --save 'DRFN_final' --testpath ../LR/LRBI --testset Urban100
CUDA_VISIBLE_DEVICES=0 python main.py --data_test MyImage --scale 3 --model DRFN --n_feats 64 --pre_train RCAN_TestCode/model/DRFN/model_best_x3.pt --test_only --save_results --chop --save 'DRFN_final' --testpath ../LR/LRBI --testset B100
CUDA_VISIBLE_DEVICES=0 python main.py --data_test MyImage --scale 3 --model DRFN --n_feats 64 --pre_train RCAN_TestCode/model/DRFN/model_best_x3.pt --test_only --save_results --chop --save 'DRFN_final' --testpath ../LR/LRBI --testset Manga109
#x4
CUDA_VISIBLE_DEVICES=0 python main.py --data_test MyImage --scale 4 --model DRFN --n_feats 64 --pre_train RCAN_TestCode/model/DRFN/model_best_x4.pt --test_only --save_results --chop --save 'DRFN_final' --testpath ../LR/LRBI --testset Set5
CUDA_VISIBLE_DEVICES=0 python main.py --data_test MyImage --scale 4 --model DRFN --n_feats 64 --pre_train RCAN_TestCode/model/DRFN/model_best_x4.pt --test_only --save_results --chop --save 'DRFN_final' --testpath ../LR/LRBI --testset Set14
CUDA_VISIBLE_DEVICES=0 python main.py --data_test MyImage --scale 4 --model DRFN --n_feats 64 --pre_train RCAN_TestCode/model/DRFN/model_best_x4.pt --test_only --save_results --chop --save 'DRFN_final' --testpath ../LR/LRBI --testset Urban100
CUDA_VISIBLE_DEVICES=0 python main.py --data_test MyImage --scale 4 --model DRFN --n_feats 64 --pre_train RCAN_TestCode/model/DRFN/model_best_x4.pt --test_only --save_results --chop --save 'DRFN_final' --testpath ../LR/LRBI --testset B100
CUDA_VISIBLE_DEVICES=0 python main.py --data_test MyImage --scale 4 --model DRFN --n_feats 64 --pre_train RCAN_TestCode/model/DRFN/model_best_x4.pt --test_only --save_results --chop --save 'DRFN_final' --testpath ../LR/LRBI --testset Manga109
#x8
#CUDA_VISIBLE_DEVICES=0 python main.py --data_test MyImage --scale 8 --model FRACTSR --n_feats 64 --pre_train ../model/RFN/model_bestD64_x8.pt --test_only --save_results --chop --save 'FRACTSR64_x8' --testpath ../LR/LRBI --testset Set5 --self_ensemble
#CUDA_VISIBLE_DEVICES=0 python main.py --data_test MyImage --scale 8 --model FRACTSR --n_feats 64 --pre_train ../model/RFN/model_bestD64_x8.pt --test_only --save_results --chop --save 'FRACTSR64_x8' --testpath ../LR/LRBI --testset Set14 --self_ensemble
#CUDA_VISIBLE_DEVICES=0 python main.py --data_test MyImage --scale 8 --model FRACTSR --n_feats 64 --pre_train ../model/RFN/model_bestD64_x8.pt --test_only --save_results --chop --save 'FRACTSR64_x8' --testpath ../LR/LRBI --testset Urban100 --self_ensemble
#CUDA_VISIBLE_DEVICES=0 python main.py --data_test MyImage --scale 8 --model FRACTSR --n_feats 64 --pre_train ../model/RFN/model_bestD64_x8.pt --test_only --save_results --chop --save 'FRACTSR64_x8' --testpath ../LR/LRBI --testset B100 --self_ensemble
#CUDA_VISIBLE_DEVICES=0 python main.py --data_test MyImage --scale 8 --model FRACTSR --n_feats 64 --pre_train ../model/RFN/model_bestD64_x8.pt --test_only --save_results --chop --save 'FRACTSR64_x8' --testpath ../LR/LRBI --testset Manga109 --self_ensemble
